<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVAlZ9AA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVAlZ9AA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVAlZ9AA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVAlZ9AA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVAlZ9AA\App_KernelDevDebugContainer([
    'container.build_hash' => 'VAlZ9AA',
    'container.build_id' => '2de3b8a2',
    'container.build_time' => 1751363355,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVAlZ9AA');
