<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYqAJsE0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYqAJsE0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYqAJsE0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYqAJsE0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYqAJsE0\App_KernelDevDebugContainer([
    'container.build_hash' => 'YqAJsE0',
    'container.build_id' => '901ad664',
    'container.build_time' => 1751710892,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYqAJsE0');
