<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7aWUvQs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7aWUvQs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7aWUvQs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7aWUvQs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7aWUvQs\App_KernelDevDebugContainer([
    'container.build_hash' => '7aWUvQs',
    'container.build_id' => '16c4af4a',
    'container.build_time' => 1751366900,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container7aWUvQs');
