nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:3000', 'http://localhost:5173']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000', 'http://localhost:5173']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['OPTIONS', 'GET', 'POST', 'PUT', 'DELETE']
            max_age: 3600
